# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e64e814a9e226c7b1a4b58ca71c5d745cef0645e60faee793fd1a1343f31aa9fe9d8fd75d438bab2ea6e5fb77f34ffb68c0e681d1a0002a1eda9da517ad6abdc

test:
  secret_key_base: 61705cd9d0e389f0ccb233fa97179df4afb1b5fd0e23382957836b9e97865a3dc7d4d5de1b9551fcc1e0865a684e050385f2b2a671e13779fd5b96c632746da1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
